In [47]:
from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim # shouldn't be nn?
from torch.autograd import Variable

In [81]:
xor = torch.tensor([[1, 1, 0, 0], [1, 0, 1, 0], [0,1,1,0]], dtype=torch.float)
print(xor)

tensor([[1., 1., 0., 0.],
        [1., 0., 1., 0.],
        [0., 1., 1., 0.]])


In [92]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 3)
        self.fc2 = nn.Linear(3, 1)
        
    
    def forward(self, x):
        x = F.tanh(self.fc1(x))
        out = self.fc2(x)
        return out 

net = Net()
print(net)

Net(
  (fc1): Linear(in_features=2, out_features=3, bias=True)
  (fc2): Linear(in_features=3, out_features=1, bias=True)
)


In [93]:
#learning_rate=0.9 #TBD alex, was missing form defineition, 0.9 is a guess.
optimizer = optim.Adam(net.parameters())
# create a loss function
criterion = nn.MSELoss()

In [96]:

#https://adventuresinmachinelearning.com/pytorch-tutorial-deep-learning/
# run the main training loop

print(xor)
inputTransposed = xor.transpose(0,1)
for r in range(1000):
    for row in inputTransposed:
        #print(row)    
        data = row[:2]
        #print(data)
        target = row[2]
        #print (target)
        optimizer.zero_grad()
        net_out = net(data)
        #print(net_out)
        loss = criterion(net_out, target)
        loss.backward()
        optimizer.step()
    
    
print("Test")
for row in inputTransposed:
    data = row[:2]
    target = row[2]
    net_out = net(data)
    print(data,net_out)
#print(net(torch.tensor([xor[0][0],xor[1][0]])))

# print(torch.t(xor)[0])
# e = Variable(xor)
# print (e.view(-1,4))

# for x in range(len(xor[0].length):
#     print(xor[0][x])
    


tensor([[1., 1., 0., 0.],
        [1., 0., 1., 0.],
        [0., 1., 1., 0.]])
Test
tensor([1., 1.]) tensor([3.6955e-06], grad_fn=<AddBackward0>)
tensor([1., 0.]) tensor([1.0000], grad_fn=<AddBackward0>)
tensor([0., 1.]) tensor([1.0000], grad_fn=<AddBackward0>)
tensor([0., 0.]) tensor([1.3113e-06], grad_fn=<AddBackward0>)


In [ ]:
epochs=10
for epoch in range(epochs):
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = Variable(data), Variable(target)
        # resize data from (batch_size, 1, 28, 28) to (batch_size, 28*28)
        data = data.view(-1, 1*2)
        optimizer.zero_grad()
        net_out = net(data)
        loss = criterion(net_out, target)
        loss.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                    epoch, batch_idx * len(data), len(train_loader.dataset),
                           100. * batch_idx / len(train_loader), loss.data[0]))